# Generated by Django 3.0.6 on 2020-05-21 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StakeHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('total_amount', models.FloatField()),
                ('order', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('receiving_reward', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_identifier', models.CharField(max_length=100)),
                ('hash', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('to', models.CharField(max_length=100)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staking.StakeHolder')),
            ],
        ),
    ]
