# Generated by Django 3.0.6 on 2020-05-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
