# Generated by Django 3.0.6 on 2020-05-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0002_transaction_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='holder',
        ),
        migrations.AddField(
            model_name='transaction',
            name='holder_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
