# Generated by Django 3.0.6 on 2020-05-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0003_auto_20200522_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_identifier',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
