# Generated by Django 3.0.6 on 2020-05-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0004_auto_20200522_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='to',
        ),
    ]
