# Generated by Django 3.0.6 on 2020-05-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0005_remove_transaction_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='type',
            field=models.CharField(default='staking', max_length=20),
            preserve_default=False,
        ),
    ]
