# Generated by Django 3.0.6 on 2020-05-30 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0006_stakeholder_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StakeHolder',
            new_name='Holder',
        ),
    ]
