# Generated by Django 3.0.6 on 2020-06-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0010_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='block',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
